### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by BartJan142** [VirtualActuary/MiscVBAFunctions#12]
Creating unit tests for the misc functions.

**Comment by BartJan142** [comment]
Unable to create a unit test for MiscCreateTextFile since it creates a physical file.

**Comment by BartJan142** [comment]
MiscDictionaryCreate gets tested in dictget from the MiscDictionary module. Is this enough testing?

**Comment by BartJan142** [comment]
MiscFreezePanes changes entries on a worksheet. Can't be unit tested?!

**Comment by BartJan142** [comment]
MiscGroupOnIndentations functions with worksheets. Can't be unit tested?

**Comment by BartJan142** [comment]
MiscNewKyes can't test NewSheetName(...)?

**Comment by BartJan142** [comment]
Can't test MiscRangeToArray since cells are required?

**Comment by BartJan142** [comment]
Can't test MiscRemoveGridLines. Worksheet required.

**Comment by BartJan142** [comment]
MiscString testing is unnecessary/difficult.

**Comment by malankriel** [comment]
> Unable to create a unit test for MiscCreateTextFile since it creates a physical file.

we can write to a file in the %temp% directory and test the file is readable and contains the content we expect

**Comment by malankriel** [comment]
> MiscFreezePanes changes entries on a worksheet. Can't be unit tested?!

We can have an Excel workbook in the tests\MiscFreezePanes folder that we can freeze panes and test if it is frozen, for example?

**Comment by malankriel** [comment]
> MiscGroupOnIndentations functions with worksheets. Can't be unit tested?

I created a test for this one. See https://github.com/VirtualActuary/MiscVBAFunctions/blob/main/MiscVBAFunctions/Modules/Test__MiscGroupOnIndentations.bas

**Comment by malankriel** [comment]
> MiscString testing is unnecessary/difficult.

We can:

- Test that the length of the output is as expected
- Test if we call it twice, that the two values are not equal

**Comment by BartJan142** [comment]
Closed in https://github.com/VirtualActuary/MiscVBAFunctions/pull/40

**Comment by malankriel** [comment]
> Closed in #40

Closed in #38 actually
