### ISSUE TITLE
MiscGetUniqueItems bug

### ISSUE THREAD

**Issue by BartJan142** [VirtualActuary/MiscVBAFunctions#13]
Function working as intended

**Comment by BartJan142** [comment]
The function works as intended but when running unit testing with Rubberduct with the test:
Asser.AreEqual SomeInteger, UBound(GetUniqueItems(SomeCollection), 1), the following error gets raised:
"[expected] and [actual] values are not the same type."

**Comment by malankriel** [comment]
UBound returns a `Long` datatype. The following should work:
`Assert.AreEqual CLng(SomeInteger), UBound(GetUniqueItems(SomeCollection), 1)`

Or 
```
Dim Expected as Long
Expected = SomeInteger
Assert.AreEqual Expected, UBound(GetUniqueItems(SomeCollection), 1)
```
