### ISSUE TITLE
add AddEarlyBindings as a Sub

### ISSUE THREAD

**Issue by malankriel** [VirtualActuary/MiscVBAFunctions#18]
https://github.com/VirtualActuary/VBALib/blob/master/add_early_bindings/EarlyBindings.bas

add to repo. 

While we're at it make this a Private Sub: https://github.com/VirtualActuary/VBALib/blob/1bc4f15622bc9edf10d528822a331a7e463f8546/add_early_bindings/EarlyBindings.bas#L69

**Comment by BartJan142** [comment]
Closed in https://github.com/VirtualActuary/MiscVBAFunctions/pull/40

**Comment by malankriel** [comment]
> Closed in #40

Closed in #38 actually :)
