### ISSUE TITLE
Can't create docs for the VBA modules.

### ISSUE THREAD

**Issue by BartJan142** [VirtualActuary/MiscVBAFunctions#37]
We got this error when attempting to run "mkdocs serve" on branch: "issue-25"

PS C:\Users\simon\devel\MiscVBAFunctions\docs> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Error reading page 'MiscVBAFunctions\Modules\Casing.md': Can't find 'templates' folder for handler 'vba'
FileNotFoundError: Can't find 'templates' folder for handler 'vba'

**Comment by heetbeet** [comment]
https://github.com/AutoActuary/mkdocstrings-vba/issues/7
