### ISSUE TITLE
Create two functions for copying tables from one workbook to another

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/MiscVBAFunctions#41]
We have a tabletodicts function to copy a table into a dict:
https://github.com/VirtualActuary/MiscVBAFunctions/blob/eea7e17ae4d4b623158b1961714e3bda806332a6/MiscVBAFunctionsLib/MiscF.bas#L1917

- Implement the inverse: dictstotable
- Implement a function to copy a table from one workbook to another, keeping number format, but valuepasting the values

**Comment by heetbeet** [comment]
@BartJan142 you can start on the first bullet point so long

**Comment by heetbeet** [comment]
![image](https://user-images.githubusercontent.com/4103775/170686362-418f5bc1-48a7-4ebc-b75e-3089ed7993b2.png)

**Comment by malankriel** [comment]
CopyExcelTableValuesToNewSheet(WB, tablename, p.getProjWB, TableNameInOutput)

```
DictsToTable(TableDicts as Collection, OutputStartRange as Range) as ListObject

Converts a TableToDicts object back to a list object.

Args:
    TableDicts: Collection of dictionaries that represents a table
    OutputStartRange: 1x1 range where the first header of the table should start

Returns:
    ListObject of the new table
```

**Comment by malankriel** [comment]
Have a wrapper function:

```
CopyExcelTableValuesToNewSheet(SourceWB as Workbook, Tablename as string, OutputWB as Workbook, TableNameInOutput as string) as ListObject

     TableDicts = DictsToTable(TableName, SourceWB)
     
     ' TODO: create new sheet, with name of table using
     Dim WS as worksheet
    set WS = OutputWB.Worksheets.add(name:=newSheetName(TableNameInOutput, OutputWB)

    set CopyExcelTableValuesToNewSheet = DictsToTable(TableDicts, WS.Range("C8")

```
