### ISSUE TITLE
Inconsistency between Excel version's LCase

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/MiscVBAFunctions#50]
https://newtonexcelbach.com/2014/03/08/problems-with-ucase-and-lcase-in-vba/

We need to find all the related functions and just make sure they are converted to `VBA.LCase`, `VBA.UCase`, etc.

**Comment by malankriel** [comment]
Also see this: https://stackoverflow.com/questions/13719687/ucase-not-being-recognised-in-vbe-what-reference-is-needed
