### ISSUE TITLE
Add FSO helpers in FSO module

### ISSUE THREAD

**Issue by BartJan142** [VirtualActuary/MiscVBAFunctions#57]
Currently, we only have documentation of our MiscVBA functions. It would be great if we could add some useful fso functions.

**Comment by malankriel** [comment]
https://github.com/VirtualActuary/MiscVBAFunctions/tree/issue-57-fso

**Comment by malankriel** [comment]
@BartJan142 we can also add those helper functions we added in the Traficc project to get all the files in a folder and sub-folder. Again if there are similar Python functions it would be good to use similar naming

**Comment by malankriel** [comment]
For now, we are not adding an shallow wrappers into the FSO module, but if for example, `Fso.FileExists` doesn't work as intended, we may write a wrapper that allows for that in this module. But nothing for now.
